[build]
  builder = "dockerfile"

[[services]]
  name = "web"
  source = "frontend"
  dockerfile = "Dockerfile"

  [services.deploy]
    startCommand = "node server.js"

[[services]]
  name = "api"
  source = "backend"
  dockerfile = "Dockerfile"

  [services.deploy]
    startCommand = "dotnet LittleMunchkins.Api.dll"
